---

- name: "Install the 'Virtualization Client' Group of tools and start libvirtd service"
  hosts: "{{ hostlist }}"
  become: true

  tasks:
    - name: Ensure 'Virtualization Client' Group is installed
      ansible.builtin.dnf:
        name: "@Virtualization Client"
        state: present

    - name: Ensure the libvirtd service is enabled and started
      ansible.builtin.systemd_service:
        name: libvirtd
        enabled: true
        state: started

...